[package]
name = "kevin_yeung_art"
version = "0.1.0"
edition = "2021"
authors = ["kevin"]
description = "A library for modeling artistic concepts."
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3